{
    'name': 'SaaS-Master:Import Modules',
    'version': '14.1.2',
    'category': 'SaaS',
    'sequence': 1,
    'license': 'OPL-1',
    'description': """Add a custom path in SaaS Settings, where you need to copy the custom modules""",
    'author': 'Pragmatic TechSoft Pvt. Ltd.',
    'website': 'http://www.pragtech.co.in',
    'summary': 'It will copy custom modules to Odoo addon path ',
    'depends': ['saas_base'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/import_module_view.xml',
        'views/res_config_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'active': False,
}
